autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

image:
  repository: duck1123/me.untethr.nostr-relay
  pullPolicy: Always
  tag: "0.2.1"

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - host: relay.localhost
    paths:
    - path: "/"
  # tls:
  # - hosts:
  #   - dinsro.localhost
  #   secretName: dinsro-tls

persistence:
  enabled: true
  size: 1G
  storageClass: 'local-path'
  # existingClaim: ''

relay:
  contact: ""
  description: If I had more time, I would have written a shorter letter.
  name: relay.localhost
  pubkey: ""
  software: https://github.com/duck1123/me.untethr.nostr-relay
  username: ""

podSecurityContext:
  fsGroup: 3434
  runAsUser: 3434
  runAsGroup: 3434
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  runAsUser: 3434
  runAsGroup: 3434
  # fsGroup: 3434

service:
  type: ClusterIP
  port: 9000

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
