{{ if .Values.autoUnlock }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "lnd.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  pwd: {{ .Values.autoUnlockPassword | b64enc }}
{{ end }}
