apiVersion: v1
kind: Service
metadata:
  name: lnd
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: rest
      port: {{ .Values.internalServices.restPort }}
      targetPort: rest
    - name: rpc
      port: {{ .Values.internalServices.rpcPort }}
      targetPort: rpc
    - name: p2p
      port: {{ .Values.externalServices.p2pPort }}
      targetPort: p2p
  selector:
    app: {{ template "lnd.name" . }}
    release: {{ .Release.Name }}
