{{- if and .Values.notebook.enabled .Values.notebook.ingress.enabled -}}
{{- $fullName := include "dinsro.fullname" . -}}
{{- $svcPort := .Values.notebook.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-notebook
  labels:
    {{- include "dinsro.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.notebook.ingress.tls }}
  tls:
    {{- range .Values.notebook.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.notebook.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: "ImplementationSpecific"
        backend:
          service:
            name: {{ $fullName }}-notebook
            port:
              number: {{ $svcPort }}
      {{- end }}
  {{- end }}
{{- end }}
