{{- if and .Values.workspaces.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dinsro.fullname" . }}-workspaces
  labels:
    {{- include "dinsro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.workspaces.service.type }}
  ports:
  - port: {{ .Values.workspaces.service.port }}
    targetPort: workspaces
    protocol: TCP
    name: workspaces
  selector:
    {{- include "dinsro.selectorLabels" . | nindent 4 }}
{{- end }}
